### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by DrewSin-4** [KasperFranz/BCLForgeLib#1]
Heyo,

I'm not sure if this Lib is still maintained, but I'd figure I'd make an issue.

It seems to crash on startup even though I have bclforgelib-1.12.2-1.1.jar installed alongside BCL.

Crash Report - https://hastebin.com/pukiketebu.sql

**Comment by KasperFranz** [comment]
From the crash report it seems like you are using v1.0 - can you please use v1 and check if you get the same error :), this is an error thrown by https://github.com/KasperFranz/BetterChunkLoader
